name: Konversi Otomatis Excel ke CSV

on:
  push:
    paths:
      - '**.[xX][lL][sS][xX]' # Kode ini membuat robot peka terhadap .xlsx maupun .XLSX

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - name: Ambil isi repositori
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instal Library Pengolah Data
      run: |
        pip install pandas openpyxl

    - name: Jalankan Script Konversi
      run: python convert.py

    - name: Simpan dan Push File CSV Kembali ke Repositori
      run: |
        git config --global user.name "GitHub Action Robot"
        git config --global user.email "actions@github.com"
        git add *.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-convert: Excel ke CSV [skip ci]" && git push)
